---

- name: Start docker compose
  shell:
    cmd: "docker-compose up -d"
  args:
    chdir: "{{ install_dir }}"
  register: compose_result
  ignore_errors: True

- name: Docker ps output - identify running containers
  shell:
    cmd: "docker ps -a | awk 'NR>1 {print $NF}' | grep '^{{ inventory_hostname }}'"
  args:
    chdir: "{{ install_dir }}"
  register: docker_ps_output

- name: Show content of docker_ps_output
  debug:
    msg:
      - container is running - {{ docker_ps_output.stdout_lines }}
